src/Dyd.BaseService.ServiceCenter.Web/Controllers/NodeController.cs
using Dyd.BaseService.ServiceCenter.Domain;
using Dyd.BaseService.ServiceCenter.Domain.Bll;
using Dyd.BaseService.ServiceCenter.Domain.Model;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using XXF.BaseService.ServiceCenter.Redis;
using XXF.BaseService.ServiceCenter.Service.Provider;
using XXF.BaseService.ServiceCenter.SystemRuntime;
using XXF.Db;

namespace Dyd.BaseService.ServiceCenter.Web.Controllers
{
    [Authorize]
    public class NodeController : Controller
    {
        /// <summary>
        /// 更新节点权重值
        /// </summary>
        /// <param name="id"></param>
        /// <param name="boostpercent"></param>
        /// <returns></returns>
        public ActionResult UpdateNodeBoostPercent(int id, int boostpercent)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
                {
                    conn.Open();
                    tb_node_bll.Instance.UpdateNodeBoostPercent(conn, id, boostpercent);
                    return Json(new { Flag = true });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Flag = false, Message = ex.Message });

            }
        }

        #region List
        /// <summary>
        /// 
        /// </summary>
        /// <param name="search">查询实体</param>
        /// <param name="pno">页码</param>
        /// <param name="pagesize">页大小</param>
        /// <returns></returns>
        public ActionResult NodeIndex(tb_node_search search)
        {
            int total = 0;
            IList<tb_node> list = new List<tb_node>();
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
            {
                conn.Open();
                IList<SelectListItem> selectList = new List<SelectListItem>();
                var serviceList = tb_service_bll.Instance.GetPageList(conn, new tb_service_search(), out total);
                foreach (var item in serviceList)
                {
                    selectList.Add(new SelectListItem { Value = item.id.ToString(), Text = item.servicename });
                }
                foreach (var item in selectList)
                {
                    if (search.serviceid.ToString() == item.Value)
                    {
                        item.Selected = true;
                    }
                }
                ViewBag.ServiceList = selectList;

                list = tb_node_bll.Instance.GetPageList(conn, search, out total);
                var pagelist = new SPagedList<tb_node>(list, search.Pno, search.PageSize, total);

                if (Request.IsAjaxRequest())
                {
                    return PartialView("_NodeIndex", pagelist);
                }
                else
                {
                    return View(pagelist);
                }
            }
        }
        #endregion

        #region Create
        /// <summary>
        /// 新增
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns></returns>
        public ActionResult NodeIndexCreate()
        {
            return View();
        }

        /// <summary>
        /// 新增
        /// </summary>
        /// <param name="model">实体</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NodeIndexCreate(tb_node model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
                {
                    conn.Open();
                    if (tb_node_bll.Instance.IsExists(conn, model))
                    {
                        return Json(new { Flag = false, Message = "！" });
                    }
                    tb_node_bll.Instance.Add(conn, model);
                    return Json(new { Flag = true, Message = "添加成功！" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Flag = false, Message = ex.Message });

            }
        }

        #endregion

        #region Edit

        /// <summary>
        /// 修改配置
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns></returns>
        public ActionResult NodeIndexEdit(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
            {
                conn.Open();
                var model = tb_node_bll.Instance.Get(conn, id);
                return View(model);
            }
        }

        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="model">实体</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NodeIndexEdit(tb_node model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
                {
                    conn.Open();
                    if (tb_node_bll.Instance.IsExists(conn, model))
                    {
                        return Json(new { Flag = false, Message = "！" });
                    }
                    tb_node_bll.Instance.Update(conn, model);
                    return Json(new { Flag = true, Message = "！" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Flag = false, Message = ex.Message });

            }
        }

        #endregion

        #region Delete
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="id">id</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NodeIndexDelete(int id)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
                {
                    conn.Open();
                    tb_node_bll.Instance.Delete(conn, id);
                    return Json(new { Flag = true, Message = "删除成功！" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Flag = false, Message = ex.Message });

            }
        }
        #endregion

        /// <summary>
        /// 节点协议
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns></returns>
        public ActionResult NodeProtocalJson(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
            {
                conn.Open();
                var model = tb_node_bll.Instance.Get(conn, id);
                return View(model);
            }
        }


        /// <summary>
        /// 重启节点
        /// </summary>
        /// <param name="id">id</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RestartNode(int id)
        {
            try
            {
                string serviceNamespace = string.Empty;
                int serviceId = 0;
                using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
                {
                    conn.Open();
                    var node = tb_node_bll.Instance.Get(conn, id);
                    if (null != node)
                    {
                        var service = tb_service_bll.Instance.Get(conn, node.serviceid);
                        if (null != service)
                        {
                            serviceNamespace = service.servicenamespace;
                            serviceId = service.id;
                        }
                    }
                }
                new RedisNetCommand(SystemConfigHelper.RedisServer).SendMessage(new ServiceNetCommand
                {
                    CommandType = EnumServiceCommandType.ServiceRestart,
                    ServiceID =serviceId,
                    NodeId = id,
                    ServiceNameSpace = serviceNamespace
                });
                return Json(new { Flag = true, Message = "重启节点成功！" });
            }
            catch (Exception ex)
            {
                return Json(new { Flag = false, Message = ex.Message });

            }
        }
    }
}

src/Dyd.BaseService.ServiceCenter.Web/Views/Node/NodeCreate.cshtml
@model Maticsoft.Model.tb_node
@{
    ViewBag.Title = "添加tb_node";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="main_content">
    <div class="top">
        <h3 class="fl">@ViewBag.Title</h3>
        <a class="fr back" href="javascript:history.go(-1)">返回</a>
    </div>
    <div class="main mt10 pt10">
        <div class="fl edit2">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <ul>
      	                    <li class="fm_item">
                        @Html.LabelFor(model => model.id)：
                        @Html.TextBoxFor(model => model.id, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.id)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.serviceid)：
                        @Html.TextBoxFor(model => model.serviceid, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.serviceid)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.sessionid)：
                        @Html.TextBoxFor(model => model.sessionid, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.sessionid)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.ip)：
                        @Html.TextBoxFor(model => model.ip, new { @maxlength = 100 })
                        @Html.ValidationMessageFor(model => model.ip)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.port)：
                        @Html.TextBoxFor(model => model.port, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.port)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.runstate)：
                        @Html.TextBoxFor(model => model.runstate, new { @maxlength = 1 })
                        @Html.ValidationMessageFor(model => model.runstate)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.nodeheartbeattime)：
                        @Html.TextBoxFor(model => model.nodeheartbeattime, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.nodeheartbeattime)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.boostpercent)：
                        @Html.TextBoxFor(model => model.boostpercent, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.boostpercent)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.errorsec)：
                        @Html.TextBoxFor(model => model.errorsec, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.errorsec)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.errorcount)：
                        @Html.TextBoxFor(model => model.errorcount, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.errorcount)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.visitsec)：
                        @Html.TextBoxFor(model => model.visitsec, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.visitsec)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.visitcount)：
                        @Html.TextBoxFor(model => model.visitcount, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.visitcount)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.threadcount)：
                        @Html.TextBoxFor(model => model.threadcount, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.threadcount)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.cpu)：
                        @Html.TextBoxFor(model => model.cpu, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.cpu)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.memory)：
                        @Html.TextBoxFor(model => model.memory, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.memory)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.filesize)：
                        @Html.TextBoxFor(model => model.filesize, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.filesize)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.createtime)：
                        @Html.TextBoxFor(model => model.createtime, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.createtime)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.interfaceversion)：
                        @Html.TextBoxFor(model => model.interfaceversion, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.interfaceversion)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.protocoljson)：
                        @Html.TextBoxFor(model => model.protocoljson, new { @maxlength = 16 })
                        @Html.ValidationMessageFor(model => model.protocoljson)
                    </li>
		  
                    <li class="fm_item" style="margin-top: 10px;">
                        <p class="box">
                            <input id="btnSave" type="button" class="btn" value="保存" />
                        </p>
                    </li>
                </ul>
            }
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $(function () {
            $("#btnSave").click(function () {
                if ($("form").valid()) {
                    var data = $("form").serialize();
                    $.ajax({
                        url: "/XX/XX/XXCreate",
                        type: "post",
                        data: data,
                        dataType: "json",
                        success: function (data) {
                            if (data.Flag) {
                                alert(data.Message);
                                window.location = "/XX/XX/XX
                                Index";
                            } else {
                                alert(data.Message);
                            }
                        }
                    });
                }
            });
        });
    </script>
}

src/Dyd.BaseService.ServiceCenter.Web/Views/Node/NodeEdit.cshtml
@model Dyd.Domain.Model.tb_order_return_config_model
@{
    ViewBag.Title = "添加tb_node";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="main_content">
    <div class="top">
        <h3 class="fl">@ViewBag.Title</h3>
        <a class="fr back" href="javascript:history.go(-1)">返回</a>
    </div>
    <div class="main mt10 pt10">
        <div class="fl edit2">
            @using (Html.BeginForm())
            {
			                                            <ul>
      	                    <li class="fm_item">
                        @Html.LabelFor(model => model.id)：
                        @Html.TextBoxFor(model => model.id, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.id)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.serviceid)：
                        @Html.TextBoxFor(model => model.serviceid, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.serviceid)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.sessionid)：
                        @Html.TextBoxFor(model => model.sessionid, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.sessionid)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.ip)：
                        @Html.TextBoxFor(model => model.ip, new { @maxlength = 100 })
                        @Html.ValidationMessageFor(model => model.ip)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.port)：
                        @Html.TextBoxFor(model => model.port, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.port)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.runstate)：
                        @Html.TextBoxFor(model => model.runstate, new { @maxlength = 1 })
                        @Html.ValidationMessageFor(model => model.runstate)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.nodeheartbeattime)：
                        @Html.TextBoxFor(model => model.nodeheartbeattime, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.nodeheartbeattime)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.boostpercent)：
                        @Html.TextBoxFor(model => model.boostpercent, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.boostpercent)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.errorsec)：
                        @Html.TextBoxFor(model => model.errorsec, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.errorsec)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.errorcount)：
                        @Html.TextBoxFor(model => model.errorcount, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.errorcount)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.visitsec)：
                        @Html.TextBoxFor(model => model.visitsec, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.visitsec)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.visitcount)：
                        @Html.TextBoxFor(model => model.visitcount, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.visitcount)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.threadcount)：
                        @Html.TextBoxFor(model => model.threadcount, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.threadcount)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.cpu)：
                        @Html.TextBoxFor(model => model.cpu, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.cpu)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.memory)：
                        @Html.TextBoxFor(model => model.memory, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.memory)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.filesize)：
                        @Html.TextBoxFor(model => model.filesize, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.filesize)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.createtime)：
                        @Html.TextBoxFor(model => model.createtime, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.createtime)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.interfaceversion)：
                        @Html.TextBoxFor(model => model.interfaceversion, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.interfaceversion)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.protocoljson)：
                        @Html.TextBoxFor(model => model.protocoljson, new { @maxlength = 16 })
                        @Html.ValidationMessageFor(model => model.protocoljson)
                    </li>
		  
                    <li class="fm_item" style="margin-top: 10px;">
                        <p class="box">
                            <input id="btnSave" type="button" class="btn" value="保存" />
                        </p>
                    </li>
                </ul>
            }
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $(function () {
            $("#btnSave").click(function () {
                if ($("form").valid()) {
                    var data = $("form").serialize();
                    $.ajax({
                        url: "/XX/XX/XXEdit",
                        type: "post",
                        data: data,
                        dataType: "json",
                        success: function (data) {
                            if (data.Flag) {
                                alert(data.Message);
                                window.location = "/XX/XX/XXIndex";
                            } else {
                                alert(data.Message);
                            }
                        }
                    });
                }
            });
        });
    </script>
}

src/Dyd.BaseService.ServiceCenter.Web/Views/Node/NodeIndex.cshtml
@model SPagedList<Dyd.BaseService.ServiceCenter.Domain.Model.tb_node>
@{
    ViewBag.Title = "服务节点";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
    var list = ViewBag.ServiceList as IList<SelectListItem>;
    list.Insert(0, new SelectListItem { Value = "0", Text = "全部" });
}
@Html.AntiForgeryToken()
<div class="main_content">
    <div class="top">
        <h3>@ViewBag.Title</h3>
    </div>
    <div class="main">
        @Html.AntiForgeryToken()
        @using (Ajax.BeginForm("NodeIndex", "Node", null, new AjaxOptions { UpdateTargetId = "ajaxList", InsertionMode = InsertionMode.Replace }, new { id = "ajaxForm" }))
        {
            <div class="pt10">
                <label>服务</label>
                @Html.DropDownList("serviceId", list)
                <label>ip地址</label>
                <input value="" type="text" name="ip" id="ip" style="width:150px;" maxlength="15" />
                <input type="submit" class="btn" value="搜索" accesskey="S" />
            </div>
        }
    </div>

    <div id="ajaxList" class="m10">
        @Html.Partial("_NodeIndex", Model)
    </div>
    <div class="layer_notice"></div>
</div>
@section Scripts{
    <script src="~/Scripts/layer/layer.js"></script>
    <link href="~/Scripts/layer/skin/layer.css" rel="stylesheet" />
    <script src="~/Scripts/jsonformat.js"></script>
}

@section footerScripts{
    @Html.SPagerScript()
    <script>
        $(function () {

            $("#ajaxList").on("click", function (event) {
                var type = $(event.target).attr("data-operate");
                switch (type) {
                    case "setDefaultProtocol": setDefaultProtocol(event.target); break;
                    case "showProtocolJson": showProtocolJson(event.target); break;
                    case "showReport": showReport(event.target); break;
                    case "restartNode": restartNode(event.target); break;
                    case "deleteItem": deleteItem(event.target); break;
                }                  
            });
        });
        

        //重启节点
        function restartNode(obj) {
            var id = $(obj).parent().parent().attr("data-id");
            if (confirm("确认设置")) {
                $.ajax({
                    url: "/Node/RestartNode",
                    type: "post",
                    data: antiToken({ id: id }),
                    dataType: "json",
                    success: function (data) {
                        if (data.Flag) {
                            alert(data.Message);
                            window.location.reload();
                        } else {
                            alert(data.Message);
                        }
                    }
                });
            }
        }

        //设置为默认协议
        function setDefaultProtocol(obj) {
            var id = $(obj).parent().parent().attr("data-id");
            if (confirm("确认设置")) {
                $.ajax({
                    url: "/ProtocolVersion/SetDefaultProtocolVersion",
                    type: "post",
                    data: antiToken({ id: id }),
                    dataType: "json",
                    success: function (data) {
                        if (data.Flag) {
                            alert(data.Message);
                            window.location.reload();
                        } else {
                            alert(data.Message);
                        }
                    }
                });
            }
        }

        function showProtocolJson(obj) {
            var id = $(obj).parent().parent().attr("data-id");
            var url = "/Node/NodeProtocalJson?id=" + id;
            window.open(url)
            //var protocalJson = $(obj).attr("data-title");
            //JsonUti.n = "<br />";
            //JsonUti.t = "&nbsp;&nbsp;&nbsp;";
            //protocalJson = JsonUti.convertToString(eval("(" + protocalJson + ")"));
            //layer.open({
            //    type: 0,
            //    title: false,
            //    scrollbar: true,
            //    closeBtn: true,
            //    shadeClose: true,
            //    skin: 'layui-layer-iframe',
            //    area: ['80%', '90%'],
            //    content: protocalJson
            //});
        }


        //禁用启用
        function showReport(obj) {
            var id = $(obj).parent().parent().attr("data-id");
            var url = "/NodeReport/NodeReportIndex?nodeid=" + id;
            window.open(url);
        }

        //删除
        function deleteItem(obj) {
            var id = $(obj).parent().parent().attr("data-id");
            if (confirm("确认删除")) {
                $.ajax({
                    url: "/Node/NodeIndexDelete",
                    type: "post",
                    data: antiToken({ id: id }),
                    dataType: "json",
                    success: function (data) {
                        if (data.Flag) {
                            alert(data.Message);
                            window.location.reload();
                        } else {
                            alert(data.Message);
                        }
                    }
                });
            }
        }

        function changeBoostPercent(id) {

            var ret = true;
            var boostpercent = $("#boostpercent" + id).val();
            if (ret) {
                $.ajax({
                    url: '/Node/UpdateNodeBoostPercent',
                    type: "post",
                    data: {
                        boostpercent: boostpercent,
                        id: id
                    },
                    success: function (data) {
                    },
                    error: function () {
                        alert("你的网络开小差了，请重试。");
                    }
                });
            }
        }
    </script>

}