src/Dyd.BaseService.ServiceCenter.Web/Controllers/ProtocolVersionController.cs
using Dyd.BaseService.ServiceCenter.Domain;
using Dyd.BaseService.ServiceCenter.Domain.Bll;
using Dyd.BaseService.ServiceCenter.Domain.Model;
using Dyd.BaseService.ServiceCenter.Web.Core;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using XXF.Db;

namespace Dyd.BaseService.ServiceCenter.Web.Controllers
{
    [Authorize]
    public class ProtocolVersionController : Controller
    {
        #region SetDefaultProtocolVersion
        /// <summary>
        /// 新增
        /// </summary>
        /// <param name="nodeId">nodeId</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SetDefaultProtocolVersion([Bind(Prefix = "id")] int nodeId)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
                {
                    conn.Open();
                    tb_service_bll.Instance.SetDefaultProtocolVersion(conn, nodeId);
                    return Json(new { Flag = true, Message = "添加成功！" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Flag = false, Message = ex.Message });

            }
        }

        #endregion



        #region List
        /// <summary>
        /// 
        /// </summary>
        /// <param name="search">查询实体</param>
        /// <param name="pno">页码</param>
        /// <param name="pagesize">页大小</param>
        /// <returns></returns>
        public ActionResult ProtocolVersionIndex(tb_protocolversion_search search)
        {
            ViewBag.ServiceId = search.serviceid;
            int total = 0;
            IList<tb_protocolversion> list = new List<tb_protocolversion>();
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
            {
                conn.Open();
                list = tb_protocolversion_bll.Instance.GetPageList(conn, search, out total);
                var pagelist = new SPagedList<tb_protocolversion>(list, search.Pno, search.PageSize, total);

                if (Request.IsAjaxRequest())
                {
                    return PartialView("_ProtocolVersionIndex", pagelist);
                }
                else
                {
                    return View(pagelist);
                }
            }
        }
        #endregion

        #region Create
        /// <summary>
        /// 新增
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns></returns>
        public ActionResult ProtocolVersionIndexCreate()
        {
            return View();
        }

        /// <summary>
        /// 新增
        /// </summary>
        /// <param name="model">实体</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ProtocolVersionIndexCreate(tb_protocolversion model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
                {
                    conn.Open();
                    if (tb_protocolversion_bll.Instance.IsExists(conn, model))
                    {
                        return Json(new { Flag = false, Message = "！" });
                    }
                    tb_protocolversion_bll.Instance.Add(conn, model);
                    return Json(new { Flag = true, Message = "添加成功！" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Flag = false, Message = ex.Message });

            }
        }

        #endregion

        #region Edit

        /// <summary>
        /// 修改配置
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns></returns>
        public ActionResult ProtocolVersionIndexEdit(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
            {
                conn.Open();
                var model = tb_protocolversion_bll.Instance.Get(conn, id);
                return View(model);
            }
        }

        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="model">实体</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ProtocolVersionIndexEdit(tb_protocolversion model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
                {
                    conn.Open();
                    if (tb_protocolversion_bll.Instance.IsExists(conn, model))
                    {
                        return Json(new { Flag = false, Message = "！" });
                    }
                    tb_protocolversion_bll.Instance.Update(conn, model);
                    return Json(new { Flag = true, Message = "！" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Flag = false, Message = ex.Message });

            }
        }

        #endregion

        #region Delete
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="id">id</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ProtocolVersionIndexDelete(int id)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
                {
                    conn.Open();
                    tb_protocolversion_bll.Instance.Delete(conn, id);
                    return Json(new { Flag = true, Message = "删除成功！" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Flag = false, Message = ex.Message });

            }
        }
        #endregion

        #region ProtocolVersionDown
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="id">id</param>
        /// <returns></returns>
        public ActionResult ProtocolVersionDown(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
            {
                conn.Open();
                var dt = DateTime.Now.ToString("yyyyMMddHHmmss");
                var protocolVersionModel = tb_protocolversion_bll.Instance.Get(conn, id);
                var serviceModel = tb_service_bll.Instance.Get(conn, protocolVersionModel.serviceid);
                string path = AppDomain.CurrentDomain.BaseDirectory.Trim('\\') + "\\ServiceSDKs\\" + dt + "\\";

                XXF.Common.IOHelper.CreateDirectory(path);
                XXF.BaseService.ServiceCenter.Client.ClientSDKHelper.ToLocalFile(serviceModel.servicenamespace, path);

                var fileName = serviceModel.servicename + dt + ".zip";
                CompressHelper.Compress(path, fileName);

                return Json(new { Url = "/ServiceSDKs/" + dt + "/" + fileName }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion
    }
}

src/Dyd.BaseService.ServiceCenter.Web/Views/ProtocolVersion/ProtocolVersionCreate.cshtml
@model Maticsoft.Model.tb_protocolversion
@{
    ViewBag.Title = "添加tb_protocolversion";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="main_content">
    <div class="top">
        <h3 class="fl">@ViewBag.Title</h3>
        <a class="fr back" href="javascript:history.go(-1)">返回</a>
    </div>
    <div class="main mt10 pt10">
        <div class="fl edit2">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <ul>
      	                    <li class="fm_item">
                        @Html.LabelFor(model => model.id)：
                        @Html.TextBoxFor(model => model.id, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.id)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.serviceid)：
                        @Html.TextBoxFor(model => model.serviceid, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.serviceid)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.version)：
                        @Html.TextBoxFor(model => model.version, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.version)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.interfaceversion)：
                        @Html.TextBoxFor(model => model.interfaceversion, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.interfaceversion)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.createtime)：
                        @Html.TextBoxFor(model => model.createtime, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.createtime)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.protocoljson)：
                        @Html.TextBoxFor(model => model.protocoljson, new { @maxlength = 16 })
                        @Html.ValidationMessageFor(model => model.protocoljson)
                    </li>
		  
                    <li class="fm_item" style="margin-top: 10px;">
                        <p class="box">
                            <input id="btnSave" type="button" class="btn" value="保存" />
                        </p>
                    </li>
                </ul>
            }
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $(function () {
            $("#btnSave").click(function () {
                if ($("form").valid()) {
                    var data = $("form").serialize();
                    $.ajax({
                        url: "/XX/XX/XXCreate",
                        type: "post",
                        data: data,
                        dataType: "json",
                        success: function (data) {
                            if (data.Flag) {
                                alert(data.Message);
                                window.location = "/XX/XX/XX
                                Index";
                            } else {
                                alert(data.Message);
                            }
                        }
                    });
                }
            });
        });
    </script>
}

src/Dyd.BaseService.ServiceCenter.Web/Views/ProtocolVersion/ProtocolVersionEdit.cshtml
@model Dyd.Domain.Model.tb_order_return_config_model
@{
    ViewBag.Title = "添加tb_protocolversion";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="main_content">
    <div class="top">
        <h3 class="fl">@ViewBag.Title</h3>
        <a class="fr back" href="javascript:history.go(-1)">返回</a>
    </div>
    <div class="main mt10 pt10">
        <div class="fl edit2">
            @using (Html.BeginForm())
            {
			                                            <ul>
      	                    <li class="fm_item">
                        @Html.LabelFor(model => model.id)：
                        @Html.TextBoxFor(model => model.id, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.id)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.serviceid)：
                        @Html.TextBoxFor(model => model.serviceid, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.serviceid)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.version)：
                        @Html.TextBoxFor(model => model.version, new { @maxlength = 4 })
                        @Html.ValidationMessageFor(model => model.version)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.interfaceversion)：
                        @Html.TextBoxFor(model => model.interfaceversion, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.interfaceversion)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.createtime)：
                        @Html.TextBoxFor(model => model.createtime, new { @maxlength = 8 })
                        @Html.ValidationMessageFor(model => model.createtime)
                    </li>
		                    <li class="fm_item">
                        @Html.LabelFor(model => model.protocoljson)：
                        @Html.TextBoxFor(model => model.protocoljson, new { @maxlength = 16 })
                        @Html.ValidationMessageFor(model => model.protocoljson)
                    </li>
		  
                    <li class="fm_item" style="margin-top: 10px;">
                        <p class="box">
                            <input id="btnSave" type="button" class="btn" value="保存" />
                        </p>
                    </li>
                </ul>
            }
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $(function () {
            $("#btnSave").click(function () {
                if ($("form").valid()) {
                    var data = $("form").serialize();
                    $.ajax({
                        url: "/XX/XX/XXEdit",
                        type: "post",
                        data: data,
                        dataType: "json",
                        success: function (data) {
                            if (data.Flag) {
                                alert(data.Message);
                                window.location = "/XX/XX/XXIndex";
                            } else {
                                alert(data.Message);
                            }
                        }
                    });
                }
            });
        });
    </script>
}

src/Dyd.BaseService.ServiceCenter.Web/Views/ProtocolVersion/ProtocolVersionIndex.cshtml
@model SPagedList<Dyd.BaseService.ServiceCenter.Domain.Model.tb_protocolversion>
@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_LayoutLayer.cshtml";
}
@Html.AntiForgeryToken()
<div class="main">
    @using (Ajax.BeginForm("ProtocolVersionIndex", "ProtocolVersion", null, new AjaxOptions { UpdateTargetId = "ajaxList", InsertionMode = InsertionMode.Replace }, new { id = "ajaxForm" }))
    {
        <input type="hidden" id="serviceid" name="serviceid" value="@ViewBag.ServiceId" />
    }
</div>

<div id="ajaxList" class="m10">
    @Html.Partial("_ProtocolVersionIndex", Model)
</div>

@section Scripts{
    <script src="~/Scripts/layer/layer.js"></script>
    <link href="~/Scripts/layer/skin/layer.css" rel="stylesheet" />
}

@section footerScripts{
    @Html.SPagerScript()
    <script>

        $(function () {

            $("#ajaxList").on("click", function (event) {
                var type = $(event.target).attr("class");
                switch (type) {
                    case "downDemo": showItem(event.target); break;
                }
            });
        });

        //下载
        function showItem(obj) {
            var id = $(obj).parent().parent().attr("data-id");
            var url = "/ProtocolVersion/ProtocolVersionDown/" + id;
            $.ajax({
                url: url,
                success: function (data) {
                    location.href = data.Url;
                },
            });

            window.location.href = url;
        }

    </script>
}

src/Dyd.BaseService.ServiceCenter.Web/Views/ProtocolVersion/_ProtocolVersionIndex.cshtml
@model SPagedList<Dyd.BaseService.ServiceCenter.Domain.Model.tb_protocolversion>

<table style="width:100%;" class="hover2" cellspacing="0" cellspadding="0" border="0">
    <tr>
        <th style="width: 10%">@Html.DisplayNameFor(model => model.version)</th>
        <th style="width: 10%">@Html.DisplayNameFor(model => model.interfaceversion)</th>
        <th style="width: 10%">@Html.DisplayNameFor(model => model.createtime)</th>
        <th style="width: 10%">@Html.DisplayNameFor(model => model.protocoljson)</th>
        <th style="width: 20%">操作</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr data-id="@item.id">

            <td>
                @item.version
            </td>
            <td>
                @item.interfaceversion
            </td>
            <td>
                @item.createtime
            </td>
            <td>
                @item.protocoljson
            </td>

            <td>
                <a class="downDemo" data-operate="downDemo" href="#">下载</a>
            </td>
        </tr>
    }
</table>
<div class="pagination">
    <div class="total fl">共<em>@Model.TotalItemCount</em>条记录</div>
    <div class="pagination-pages">
        @Html.SPager(Model, "pno", "pager_page", "#ajaxList", "#ajaxForm")
    </div>
</div>