src/Dyd.BaseService.ServiceCenter.Web/Controllers/NodeReportController.cs
using Dyd.BaseService.ServiceCenter.Domain;
using Dyd.BaseService.ServiceCenter.Domain.Bll;
using Dyd.BaseService.ServiceCenter.Domain.Model;
using Dyd.BaseService.ServiceCenter.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using XXF.Db;

namespace Dyd.BaseService.ServiceCenter.Web.Controllers
{
    [Authorize]
    public class NodeReportController : Controller
    {
        #region List
        /// <summary>
        /// 
        /// </summary>
        /// <param name="search">查询实体</param>
        /// <param name="pno">页码</param>
        /// <param name="pagesize">页大小</param>
        /// <returns></returns>
        public ActionResult NodeReportIndex(tb_node_report_model_search search)////所有参数memorysize,errorcount,connectioncount,visitcount,processthreadcount,processcpuper,
        {
            List<TimeChartModel> ms = new List<TimeChartModel>();
            if (string.IsNullOrWhiteSpace(search.columns))
            {
                search.columns = "processcpuper,memorysize,processthreadcount,visitcount,connectioncount,errorcount,";
            }
            if (string.IsNullOrWhiteSpace(search.columns))
            {
                return View(ms);
            }

            if (string.IsNullOrEmpty(search.queryDay))
            {
                search.queryDay = DateTime.Now.ToString("yyyy-MM-dd");
            }
            if (string.IsNullOrWhiteSpace(search.datatype))
            {
                search.datatype = TimeChartDataType.avg.ToString();
            }

            ViewBag.datatype = search.datatype;
            ViewBag.columns = search.columns;
            ViewBag.nodeid = search.nodeid;
            ViewBag.BeginDate = search.queryDay;
            search.TimeChartType = "Day";


            TimeChartDataType chartdatatype = (TimeChartDataType)Enum.Parse(typeof(TimeChartDataType), search.datatype);
            TimeChartType charttype = TimeChartType.Day;

            var startDate = DateTime.Parse(search.queryDay).Date;

            SPagedList<tb_node_report_model> pagelist;
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterReportConnectString))
            {
                conn.Open();
                int total = 0;
                IList<tb_node_report_model> list = new List<tb_node_report_model>();
                list = tb_node_report_bll.Instance.GetList(conn, search);
                pagelist = new SPagedList<tb_node_report_model>(list, search.Pno, search.PageSize, total);
            }

            string[] cs = search.columns.TrimEnd(',').Split(',');
            string unit = string.Empty;
            foreach (var c in cs)
            {
                string Title = string.Empty;

                Dictionary<DateTime, double> dic = new Dictionary<DateTime, double>();

                if (c == "errorcount")
                {
                    Title = "错误数量";
                    unit = "个";
                    foreach (var item in pagelist)
                    {
                        dic.Add(Convert.ToDateTime(item.createtime), Convert.ToDouble(item.errorcount));
                    }
                }

                if (c == "connectioncount")
                {
                    Title = "当前连接数";
                    unit = "个";
                    foreach (var item in pagelist)
                    {
                        dic.Add(Convert.ToDateTime(item.createtime), Convert.ToDouble(item.connectioncount));
                    }
                }

                if (c == "visitcount")
                {
                    unit = "次";
                    Title = "访问次数";
                    foreach (var item in pagelist)
                    {
                        dic.Add(Convert.ToDateTime(item.createtime), Convert.ToDouble(item.visitcount));
                    }
                }

                if (c == "processthreadcount")
                {
                    unit = "个";
                    Title = "线程数";
                    foreach (var item in pagelist)
                    {
                        dic.Add(Convert.ToDateTime(item.createtime), Convert.ToDouble(item.processthreadcount));
                    }
                }

                if (c == "processcpuper")
                {
                    unit = "百分比";
                    Title = "cpu占用";
                    foreach (var item in pagelist)
                    {
                        dic.Add(Convert.ToDateTime(item.createtime), Convert.ToDouble(item.processcpuper.ToString("N2")));
                    }
                }

                if (c == "memorysize")
                {
                    unit = "M";
                    Title = "内存占用";
                    foreach (var item in pagelist)
                    {
                        dic.Add(Convert.ToDateTime(item.createtime), Convert.ToDouble(item.memorysize.ToString("N2")));
                    }
                }

                if (c == "")
                    continue;
                var model = new TimeChartModel();
                model.DataType = chartdatatype;
                model.Type = charttype;
                model.StartDate = startDate;
                model.Key = c;
                model.Title = Title;
                model.UnitText = unit;

                model.SubTitle = model.Title + "【" + model.DataType.ToString() + "】值统计图";
                if (model.Type == TimeChartType.Day)
                {
                    model.PointInterval = "60 * 1000";
                    model.EndDate = model.StartDate.AddDays(1);
                    model.MaxZoom = "60 * 60 * 1000";
                    model.SubTitle += ",采集单位【分钟】";
                }
                else if (model.Type == TimeChartType.Month)
                {
                    model.PointInterval = "24 * 60 * 60 * 1000";
                    model.EndDate = model.StartDate.AddMonths(1);
                    model.MaxZoom = "10 * 24 * 60 * 60 * 1000";
                    model.SubTitle += ",采集单位【天】";
                }
                else if (model.Type == TimeChartType.Year)
                {
                    model.PointInterval = "24 * 60 * 60 * 1000";
                    model.EndDate = model.StartDate.AddYears(1);
                    model.MaxZoom = "10 * 24 * 60 * 60 * 1000";
                    model.SubTitle += ",采集单位【天】";
                }

                DateTime dtbegin = model.StartDate;
                DateTime dtend = model.EndDate;
                while (true)
                {
                    if (!dic.ContainsKey(dtbegin))
                    {
                        dic.Add(dtbegin, 0);
                    }
                    if (model.Type == TimeChartType.Day)
                        dtbegin = dtbegin.AddMinutes(1);
                    else
                        dtbegin = dtbegin.AddDays(1);
                    if (dtbegin >= dtend)
                        break;
                }
                model.DataJson = new XXF.Serialization.JsonHelper().Serializer(dic.OrderBy(c1 => c1.Key).Select(c1 => c1.Value));
                ms.Add(model);
            }
            return View(ms);
        }
        #endregion
    }
}

src/Dyd.BaseService.ServiceCenter.Web/Views/NodeReport/NodeReportIndex.cshtml
@model  List<Dyd.BaseService.ServiceCenter.Web.Models.TimeChartModel>
@{
    ViewBag.Title = "节点监控报表";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
@Html.AntiForgeryToken()
<div class="main_content">
    <div class="top">
        <h3>@ViewBag.Title</h3>
    </div>
    <div class="main">
        @using (Html.BeginForm("NodeReportIndex", "NodeReport", FormMethod.Post))
        {
            <div class="pt10">
                <label>节点id</label>
                <input value="@ViewBag.nodeid" type="text" name="nodeid" id="nodeid" style="width:150px;" maxlength="15" />
                <label>时间</label>
                <input value="@ViewBag.BeginDate" type="text" name="queryDay" id="queryDay" style="width:150px;" onclick="WdatePicker()" maxlength="15" />
                <label>类型</label>
                <select name="datatype">
                    <option value="avg" @(ViewBag.datatype + "" == "avg" ? "selected='selected'" : "")>平均</option>
                    <option value="max" @(ViewBag.datatype + "" == "max" ? "selected='selected'" : "")>最大</option>
                    <option value="min" @(ViewBag.datatype + "" == "min" ? "selected='selected'" : "")>最小</option>
                </select>
                <input type="submit" class="btn" value="搜索" onclick="return search();" accesskey="S" />
            </div>
            <div class="pt10">
                <label>显示</label>
                <input type="checkbox" onclick="chooseAll(this); " value='' />
                <input type="hidden" name="columns" id="columns" value="@ViewBag.columns" />
                <input type="checkbox" value="processcpuper" />cpu占用
                <input type="checkbox" value="memorysize" />内存占用
                <input type="checkbox" value="processthreadcount" />线程数
                <input type="checkbox" value="visitcount" />访问次数
                <input type="checkbox" value="connectioncount" />当前连接数
                <input type="checkbox" value="errorcount" />错误数量
            </div>
        }
    </div>

    <div id="ajaxList" class="m10">
    </div>

    <div>
        @foreach (var m in Model)
        {
            <div id="container@(m.Key)" style="width:48%;height:400px; float:left"></div>
        }
    </div>
</div>
@section Scripts{
    <script type="text/javascript" src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
    <script src="~/Content/js/chart.js"></script>
    <script>
        $(function () {
            $("[type='checkbox']").each(function (i) {
                if ($('#columns').val().indexOf($(this).val()) > -1 && $(this).val() != '') {
                    $(this).attr("checked", true);
                }
            });
        });

        function chooseAll(item) {
            if ($(item).attr("checked")) {
                $("[type='checkbox']").attr("checked", true);
            }
            else
                $("[type='checkbox']").attr("checked", false);
        }

        function search() {
            var choosed = '';
            $("[type='checkbox']").each(function (i) {
                if ($(this).attr("checked") && $(this).val() != '') {
                    choosed += $(this).val() + ',';
                }
            });
            $("#columns").val(choosed);
            return true;
        }
        $(function () {
            Highcharts.setOptions({
                global: {
                    useUTC: true
                }
            })

            @foreach (var m in Model)
          {
              var c = @"$('#container'+'{key}').highcharts({
            chart: {
                zoomType: 'x',
                spacingRight: 20
            },
            title: {
                text: '{title}'
            },
            credits : {
                enabled:false//不显示highCharts版权信息
            },
            subtitle: {
                text: document.ontouchstart === undefined ?
                    '{subtitle}' :
                    'Pinch the chart to zoom in'
            },
            xAxis: {
                type: 'datetime',
                maxZoom: {maxzoom}, // fourteen days
                //tickInterval:60*60*1000,
                //max:Date.UTC({enddate}),
                dateTimeLabelFormats:{day: '%b月%e日',month: '%y年%b月' ,year: '%Y'},
                title: {
                    text: null
                }
            },
            yAxis: {
                title: {
                    text: '{ytitle}'
                }
            },
            tooltip: {
                shared: true
            },
            legend: {
                enabled: false
            },
            plotOptions: plotOptions1,

            series: [{
                type: 'area',
                name: '{unittext}',
                pointInterval:  {pointinterval},
                pointStart: Date.UTC({startdate}),
                data: {datajson}
            }]
        });".Replace("{key}", m.Key).Replace("{title}", m.Title).Replace("{subtitle}", m.SubTitle)
                  .Replace("{datajson}", m.DataJson).Replace("{ytitle}", m.YTitle)
                  .Replace("{startdate}", m.StartDate.ToString("yyyy,MM,dd"))
                  .Replace("{unittext}", m.UnitText)
                  .Replace("{maxzoom}", m.MaxZoom)
                  .Replace("{pointinterval}", m.PointInterval)
                  .Replace("{enddate}", m.EndDate.ToString("yyyy,MM,dd"));
        @Html.Raw(c)
          }
        });

    </script>

}

@section footerScripts{
}

src/Dyd.BaseService.ServiceCenter.Web/Views/NodeReport/_NodeReportIndex.cshtml
@model SPagedList<Dyd.BaseService.ServiceCenter.Domain.Model.tb_node_report_model>
<table style="width:100%;" class="hover2" cellspacing="0" cellspadding="0" border="0">
    <tr>
        <th style="width: 10%">@Html.DisplayNameFor(model => model.id)</th>
        <th style="width: 10%">@Html.DisplayNameFor(model => model.nodeid)</th>
        <th style="width: 10%">@Html.DisplayNameFor(model => model.createtime)</th>
        <th style="width: 10%">@Html.DisplayNameFor(model => model.errorcount)</th>
        <th style="width: 10%">@Html.DisplayNameFor(model => model.connectioncount)</th>
        <th style="width: 10%">@Html.DisplayNameFor(model => model.visitcount)</th>
        <th style="width: 10%">@Html.DisplayNameFor(model => model.processthreadcount)</th>
        <th style="width: 10%">@Html.DisplayNameFor(model => model.processcpuper)</th>
        <th style="width: 10%">@Html.DisplayNameFor(model => model.memorysize)</th>

        <th style="width: 20%">操作</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr data-id="@item.id">
            <td>
                @item.id
            </td>
            <td>
                @item.nodeid
            </td>
            <td>
                @item.createtime
            </td>
            <td>
                @item.errorcount
            </td>
            <td>
                @item.connectioncount
            </td>
            <td>
                @item.visitcount
            </td>
            <td>
                @item.processthreadcount
            </td>
            <td>
                @item.processcpuper
            </td>
            <td>
                @item.memorysize
            </td>

            <td>
                <a class="editItem" data-operate="editItem" href="#">编辑</a>
                <a class="showItem" data-operate="showItem" href="#">查看</a>
                <a class="deleteItem" data-operate="deleteItem" href="#">删除</a>
            </td>
        </tr>
    }
</table>
<div class="pagination">
    <div class="total fl">共<em>@Model.TotalItemCount</em>条记录</div>
    <div class="pagination-pages">
        @Html.SPager(Model, "pno", "pager_page", "#ajaxList", "#ajaxForm")
    </div>
</div>