src/Dyd.BaseService.ServiceCenter.Web/Controllers/SystemConfigController.cs
using Dyd.BaseService.ServiceCenter.Domain;
using Dyd.BaseService.ServiceCenter.Domain.Bll;
using Dyd.BaseService.ServiceCenter.Domain.Model;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using XXF.Db;

namespace Dyd.BaseService.ServiceCenter.Web.Controllers
{
    [Authorize]
    public class SystemConfigController : Controller
    {

        #region List
        /// <summary>
        /// 
        /// </summary>
        /// <param name="search">查询实体</param>
        /// <param name="pno">页码</param>
        /// <param name="pagesize">页大小</param>
        /// <returns></returns>
        public ActionResult SystemConfigIndex(tb_system_config_Search search)
        {
            int total = 0;
            IList<tb_system_config> list = new List<tb_system_config>();
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
            {
                conn.Open();
                list = tb_system_config_bll.Instance.GetPageList(conn, search, out total);
                var pagelist = new SPagedList<tb_system_config>(list, search.Pno, search.PageSize, total);

                if (Request.IsAjaxRequest())
                {
                    return PartialView("_SystemConfigIndex", pagelist);
                }
                else
                {
                    return View(pagelist);
                }
            }
        }
        #endregion

        #region Create
        /// <summary>
        /// 新增
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns></returns>
        public ActionResult SystemConfigCreate()
        {
            return View();
        }

        /// <summary>
        /// 新增
        /// </summary>
        /// <param name="model">实体</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SystemConfigCreate(tb_system_config model)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
                {
                    conn.Open();
                    if (tb_system_config_bll.Instance.IsExists(conn, model))
                    {
                        return Json(new { Flag = false, Message = "配置重复！" });
                    }
                    var id = tb_system_config_bll.Instance.Add(conn, model);
                    tb_log_bll.Instance.Add(conn, string.Format("{0}|Id:{1}|Key:{2}|Value:{3}", "添加系统配置", id, model.key, model.value));

                    return Json(new { Flag = true, Message = "添加成功！" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Flag = false, Message = ex.Message });

            }
        }

        #endregion

        #region Edit

        /// <summary>
        /// 修改配置
        /// </summary>
        /// <param name="id">Id</param>
        /// <returns></returns>
        public ActionResult SystemConfigEdit(int id)
        {
            using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
            {
                conn.Open();
                var model = tb_system_config_bll.Instance.Get(conn, id);
                return View(model);
            }
        }

        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="model">实体</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SystemConfigEdit(tb_system_config model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
                {
                    conn.Open();
                    if (tb_system_config_bll.Instance.IsExists(conn, model))
                    {
                        return Json(new { Flag = false, Message = "配置重复！" });
                    }

                    tb_system_config_bll.Instance.Update(conn, model);
                    tb_log_bll.Instance.Add(conn, string.Format("{0}|Id:{1}|Key:{2}|Value:{3}", "添加系统配置", model.id, model.key, model.value));
                    return Json(new { Flag = true, Message = "修改成功！" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Flag = false, Message = ex.Message });

            }
        }

        #endregion

        #region Delete
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="id">id</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SystemConfigDelete(int id)
        {
            try
            {
                using (DbConn conn = DbConfig.CreateConn(DataConfig.ServiceCenterConnectString))
                {
                    conn.Open();
                    var model = tb_system_config_bll.Instance.Get(conn, id);
                    tb_system_config_bll.Instance.Delete(conn, id);
                    tb_log_bll.Instance.Add(conn, string.Format("{0}|Id:{1}|Key:{2}|Value:{3}", "删除系统配置", model.id, model.key, model.value));
                    return Json(new { Flag = true, Message = "删除成功！" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Flag = false, Message = ex.Message });

            }
        }
        #endregion
    }
}

src/Dyd.BaseService.ServiceCenter.Web/Views/SystemConfig/SystemConfigCreate.cshtml
@model Dyd.BaseService.ServiceCenter.Domain.Model.tb_system_config
@{
    ViewBag.Title = "添加系统配置";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="main_content">
    <div class="top">
        <h3 class="fl">@ViewBag.Title</h3>
        <a class="fr back" href="javascript:history.go(-1)">返回</a>
    </div>
    <div class="main mt10 pt10">
        <div class="fl edit2">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <ul class="mydetail">
                    <li class="fm_item">
                        @Html.LabelFor(model => model.key)：
                        @Html.TextBoxFor(model => model.key, new { @maxlength = 200 })
                        @Html.ValidationMessageFor(model => model.key)
                    </li>
                    <li class="fm_item">
                        @Html.LabelFor(model => model.value)：
                        @Html.TextBoxFor(model => model.value, new { @maxlength = 500 })
                        @Html.ValidationMessageFor(model => model.value)
                    </li>
                    <li class="fm_item">
                        @Html.LabelFor(model => model.remark)：
                        @Html.TextAreaFor(model => model.remark, new { @rows = 10, @maxlength = 1000 })
                        @Html.ValidationMessageFor(model => model.remark)
                    </li>

                    <li class="fm_item" style="margin-top: 10px;">
                        <p class="box">
                            <input id="btnSave" type="button" class="btn" value="保存" />
                        </p>
                    </li>
                </ul>
            }
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $(function () {
            $("#btnSave").click(function () {
                if ($("form").valid()) {
                    var data = $("form").serialize();
                    $.ajax({
                        url: "/SystemConfig/SystemConfigCreate",
                        type: "post",
                        data: data,
                        dataType: "json",
                        success: function (data) {
                            if (data.Flag) {
                                alert(data.Message);
                                window.location = "/SystemConfig/SystemConfigIndex";
                            } else {
                                alert(data.Message);
                            }
                        }
                    });
                }
            });
        });
    </script>
}

src/Dyd.BaseService.ServiceCenter.Web/Views/SystemConfig/SystemConfigEdit.cshtml
@model Dyd.BaseService.ServiceCenter.Domain.Model.tb_system_config
@{
    ViewBag.Title = "修改系统配置";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="main_content">
    <div class="top">
        <h3 class="fl">@ViewBag.Title</h3>
        <a class="fr back" href="javascript:history.go(-1)">返回</a>
    </div>
    <div class="main mt10 pt10">
        <div class="fl edit2">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.id)
                <ul class="mydetail">
                    <li class="fm_item">
                        @Html.LabelFor(model => model.key)：
                        @Html.TextBoxFor(model => model.key, new { @maxlength = 200 })
                        @Html.ValidationMessageFor(model => model.key)
                    </li>
                    <li class="fm_item">
                        @Html.LabelFor(model => model.value)：
                        @Html.TextBoxFor(model => model.value, new { @maxlength = 500 })
                        @Html.ValidationMessageFor(model => model.value)
                    </li>
                    <li class="fm_item">
                        @Html.LabelFor(model => model.remark)：
                        @Html.TextAreaFor(model => model.remark, new { @rows = 10, @maxlength = 1000 })
                        @Html.ValidationMessageFor(model => model.remark)
                    </li>

                    <li class="fm_item" style="margin-top: 10px;">
                        <p class="box">
                            <input id="btnSave" type="button" class="btn" value="保存" />
                        </p>
                    </li>
                </ul>
            }
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $(function () {
            $("#btnSave").click(function () {
                if ($("form").valid()) {
                    var data = $("form").serialize();
                    $.ajax({
                        url: "/SystemConfig/SystemConfigEdit",
                        data: addAntiForgeryToken(data),
                        type: "post",
                        success: function (data) {
                            if (data.Flag) {
                                alert(data.Message);
                                window.location.href = "/SystemConfig/SystemConfigIndex";
                            } else {
                                alert(data.Message);
                            }
                        }
                    });
                }
            });
        });
    </script>
}

src/Dyd.BaseService.ServiceCenter.Web/Views/SystemConfig/SystemConfigIndex.cshtml
@model SPagedList<Dyd.BaseService.ServiceCenter.Domain.Model.tb_system_config>
@{
    ViewBag.Title = "系统配置";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
@Html.AntiForgeryToken()
<div class="main_content">
    <div class="top">
        <h3>@ViewBag.Title</h3>
    </div>
    <div class="box ml10">
        @Html.ActionLink("新增", "SystemConfigCreate", "SystemConfig", null, new { @class = "btn", id = "addLink" })
    </div>
    <div class="main">
        @using (Ajax.BeginForm("SystemConfigIndex", "SystemConfig", null, new AjaxOptions { UpdateTargetId = "ajaxList", InsertionMode = InsertionMode.Replace }, new { id = "ajaxForm" }))
        {
            <div class="pt10">
                <label>键</label>
                <input value="" type="text" name="key" id="key" style="width:150px;" maxlength="15" />
                <label>值</label>
                <input value="" type="text" name="value" id="value" style="width:150px;" maxlength="15" />
                <label>备注</label>
                <input value="" type="text" name="remark" id="remark" style="width:150px;" maxlength="15" />
                <input type="submit" class="btn" value="搜索" accesskey="S" />
            </div>
        }
    </div>

    <div id="ajaxList" class="m10">
        @Html.Partial("_SystemConfigIndex", Model)
    </div>
</div>
@section Scripts{
}

@section footerScripts{
    @Html.SPagerScript()
    <script>

        $(function () {

            $("#ajaxList").on("click", function (event) {
                var type = $(event.target).attr("class");
                switch (type) {
                    case "editItem": editItem(event.target); break;
                    case "deleteItem": deleteItem(event.target); break;
                }
            });
        });

        //编辑
        function editItem(obj) {
            var id = $(obj).parent().parent().attr("data-id");
            var url = "/SystemConfig/SystemConfigEdit/" + id;
            window.location.href = url;
        }

        //删除
        function deleteItem(obj) {
            var id = $(obj).parent().parent().attr("data-id");
            if (confirm("确认删除")) {
                $.ajax({
                    url: "/SystemConfig/SystemConfigDelete",
                    type: "post",
                    data: antiToken({ id: id }),
                    dataType: "json",
                    success: function (data) {
                        if (data.Flag) {
                            alert(data.Message);
                            window.location.reload();
                        } else {
                            alert(data.Message);
                        }
                    }
                });
            }
        }
    </script>
}

src/Dyd.BaseService.ServiceCenter.Web/Views/SystemConfig/_SystemConfigIndex.cshtml
@model SPagedList<Dyd.BaseService.ServiceCenter.Domain.Model.tb_system_config>
<table style="width:100%;" class="hover2" cellspacing="0" cellspadding="0" border="0">
    <tr>
        <th style="width: 5%">@Html.DisplayNameFor(model => model.id)</th>
        <th style="width: 20%">@Html.DisplayNameFor(model => model.key)</th>
        <th style="width: 20%">@Html.DisplayNameFor(model => model.value)</th>
        <th style="width: 45%">@Html.DisplayNameFor(model => model.remark)</th>

        <th style="width: 10%">操作</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr data-id="@item.id">
            <td>
                @item.id
            </td>
            <td>
                @item.key
            </td>
            <td>
                @item.value
            </td>
            <td>
                @item.remark
            </td>

            <td>
                <a class="editItem" data-operate="editItem" href="#">编辑</a>
                <a class="deleteItem" data-operate="deleteItem" href="#">删除</a>
            </td>
        </tr>
    }
</table>
<div class="pagination">
    <div class="total fl">共<em>@Model.TotalItemCount</em>条记录</div>
    <div class="pagination-pages">
        @Html.SPager(Model, "pno", "pager_page", "#ajaxList", "#ajaxForm")
    </div>
</div>